# .gitlab-ci.yml
#
# Copyright (c) 2016 Zach Deibert.
# All Rights Reserved.

stages:
    - build
    - package

cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
        - bin/
        - obj/
        - Com.Latipium.Core.1.0.nupkg

buildDebug:
    image: mono
    script:
        - nuget restore -SolutionDirectory ..
        - echo "$SIGNING_KEY" | base64 -d > ../Latipium.snk
        - xbuild Com.Latipium.Core.csproj /property:Configuration=Debug
        - rm ../Latipium.snk
    stage: build
    only:
        - development
    tags:
        - docker
        - latipium
    artifacts:
        name: "$CI_BUILD_REF_NAME-build"
        paths:
            - bin/Debug/

buildRelease:
    image: mono
    script:
        - nuget restore -SolutionDirectory ..
        - echo "$SIGNING_KEY" | base64 -d > ../Latipium.snk
        - xbuild Com.Latipium.Core.csproj /property:Configuration=Release
        - rm ../Latipium.snk
    stage: build
    only:
        - master
    tags:
        - docker
        - latipium
    artifacts:
        name: "$CI_BUILD_REF_NAME-build"
        paths:
            - bin/Release/

packageDebug:
    image: mono
    script:
        - nuget pack Debug.nuspec
    stage: package
    only:
        - development
    tags:
        - docker
        - latipium
    artifacts:
        name: "$CI_BUILD_REF_NAME-pkg"
        paths:
            - Com.Latipium.Core.1.0.nupkg

packageRelease:
    image: mono
    script:
        - nuget pack Release.nuspec
    stage: package
    only:
        - master
    tags:
        - docker
        - latipium
    artifacts:
        name: "$CI_BUILD_REF_NAME-pkg"
        paths:
            - Com.Latipium.Core.1.0.nupkg
